
services:
  backend:
    build: .
    ports:
      - "7000:7000"
    environment:
      - REDIS_HOST=redis
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"